spring:
  application:
    name: spring-boot-modular-starterkit-java

  # Module: user-service
  cloud:
    azure:
      active-directory:
        enabled: true
        credential:
          client-id: ${AZURE_AD_CREDENTIAL_CLIENT_ID}
        app-id-uri: ${AZURE_AD_APP_ID_URI}
  data:
    mongodb:
      uri: "mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:27017/"
      database: ${MONGODB_DATABASE}
      auto-index-creation: true

# Module: integration-kafka-avro
kafka:
  consumer:
    enabled: false
  topics:
    create-user-events: create-user-events

# Module: user-service
security:
  enabled: false