spring:
  application:
    name: spring-boot-modular-starterkit-java

  # Module: integration-kafka-avro
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      schema:
        registry:
          url: ${KAFKA_SCHEMA_REGISTRY}
    consumer:
      group-id: spring-boot-gradle-java-multi-module-boilerplate
      enable-auto-commit: true
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

  # Module(s): user-service
  cloud:
    azure:
      active-directory:
        enabled: true
        credential:
          client-id: ${AZURE_AD_CREDENTIAL_CLIENT_ID}
        app-id-uri: ${AZURE_AD_APP_ID_URI}
  data:
    mongodb:
      uri: "mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:27017/"
      database: ${MONGODB_DATABASE}
      auto-index-creation: true

# Module(s): integration-kafka-avro
kafka:
  consumer:
    enabled: true
  topics:
    create-user-events: create-user-events

# Module: user-service
security:
  enabled: false