spring:
  application:
    name: spring-boot-modular-starterkit-java

  # Module: integration-kafka-avro
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      schema:
        registry:
          url: ${KAFKA_SCHEMA_REGISTRY}
    consumer:
      group-id: spring-boot-gradle-java-multi-module-boilerplate
      enable-auto-commit: true
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

  # Module(s): user-service
  cloud:
    azure:
      active-directory:
        enabled: true
        credential:
          client-id: ${AZURE_AD_CREDENTIAL_CLIENT_ID}
        app-id-uri: ${AZURE_AD_APP_ID_URI}
  datasource:
    platform: postgres
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database: POSTGRESQL
    # https://docs.spring.io/spring-boot/docs/1.1.0.M1/reference/html/howto-database-initialization.html
    generate:
      ddl: false
    hibernate:
      ddl-auto: update # NOTE: Flyway database migrations are executed on startup

# Module(s): integration-kafka-avro
kafka:
  consumer:
    enabled: true
  topics:
    create-user-events: create-user-events